version: 2.1


jobs:
    test:
        docker:
            - image: python:3.7.8-alpine3.12
        steps:
            - checkout
            - run:
                name: Instalando Dependencias
                command: pip install -r requirements.txt
            - run:
                name: Realizando Tests Unitarios
                command: python -m unittest -v

workflows:
    test-deploy:
        jobs:
            - test